version: "3.9"

services:

  mysql:
    image: mysql:8.0
    container_name: solare-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: solare_db
      MYSQL_USER: solare_user
      MYSQL_PASSWORD: solare_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  solare-backend:
    build: .
    container_name: solare-backend
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/solare_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: solare_user
      SPRING_DATASOURCE_PASSWORD: solare_pass

      WOMPI_ENABLED: false
      WOMPI_URL: https://sandbox.wompi.co/v1
      WOMPI_PUBLIC_KEY: fake
      WOMPI_PRIVATE_KEY: fake

volumes:
  mysql_data:
